### ISSUE TITLE
CSS 模拟打字动画

### ISSUE THREAD

**Issue by imhxc** [imhxc/imhxc.github.io#5]
## 前言

或许你看过网上的一些模拟打字的效果，深究其原理，会发现很简单，核心原理就是逐帧动画、闪烁效果。

或许你会想到使用 JavaScript 来实现，固然，这是一个办法，但是这会产生一段又臭又长、难以理解的代码。

这里，我们可以使用纯 CSS 来实现。

## 解决方案

> 核心思路将一段文案放置到可拉伸的容器中。

````html
<h1>这是一段模拟的打字效果。</h1>
````

````css
@keyframes typing {
    from { width: 0 }
}

h1 {
    width: 22em;
    overflow: hidden;
    white-space: nowrap;
    animation: typing 4s;
}
````

### 逐字效果

前面代码并不是逐字显示的，为了解决这一问题，我们可是使用 `steps()` 来解决：

````css
h1 {
    width: 22em;
    overflow: hidden;
    white-space: nowrap;
    animation: typing 4s steps(22);
}
````

### 光标闪烁效果

是不是觉得还差一些，对，就是差一个光标输入闪烁效果。这里，我们可以使用为元素来生成一个光标，并通过 `opacity` 属性来实现闪烁效果。

当然，也可以用右边框来模拟光标效果，这样就可以把有限的伪元素资源节省下来留作他用。

````css
@keyframes typing {
    from { width: 0 }
}
@keyframes caret {
    50% { border-color: transparent; }
}
h1 {
    width: 12em;
    overflow: hidden;
    white-space: nowrap;
    border-right: .05em solid;
    animation: typing 5s steps(12), caret .5s steps(1) infinite;
}
````

## 总结

寥寥数行 CSS 代码，便可以实现一段模拟打字的效果，其核心就是借助 `em` 单位及 `steps()` 属性 实现逐帧动画，并利用 `infinite` 属性创建一个不断循环闪烁的光标。

另外，这里我们使用的是 `em` 单位，设置 `h1` 宽度为 `12em`，12 这个数字是根据 `h1` 标签内的字符串长度得来的。

不过，如果不是中文，建议使用 `ch` 单位来设置 `width`。

对于一段文字夹杂了中文、英文等其他字符，会发生一些预期之外的现象，所以，该解决方案也有一定的局限性。
