### ISSUE TITLE
实现一个环境路径动画

### ISSUE THREAD

**Issue by imhxc** [imhxc/imhxc.github.io#7]
## 设置头像按照环形持续运动

定义一个简单的 HTML 结构：

````html
<div class="wrap">
  <img class="avatar" src="https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=320178652,790985626&fm=27&gp=0.jpg" />
</div>
````

我们先来写下 CSS：

````css
.wrap {
  width: 300px;
  height: 300px;
  border-radius: 50%;
  background: #007fff;
}
.avatar {
  display: block;
  margin: 0 auto;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  transform-origin: 50% 150px; /** 150px 是因为父元素 .wrap 宽度等于 300px */
  animation: spin 8s infinite linear;
}
@keyframes spin {
  to { transform: rotate(1turn); }
}
````

这里要解释一点，即 .avatar 需要居中，所以才设置了 margin: 0 auto，这样我们在设置transform-origin: 50% 150px 才能使其原点居于父元素中心点，从而围绕该原点旋转。

到现在为止，我们已经成功让该头像围绕环形路径进行旋转了，但是我们还想进一步优化。

如果你仔细观察，会发现，头像在围绕环形运动的时候，其自身也会进行旋转，这就会到导致其旋转到 180 度的时候（即 .wrap 底边中心处），头像朝向下方，我们想要其头像不管何时其朝向都为上，换句话说，头像自身不允许旋转。

或许你可能会说，这并不会影响什么，但是，如果是文字呢？那岂不是影响也阅读。

## 实现头像朝向始终朝上，取消头像自身旋转

或许你使用或见过下面这段 CSS：

````css
.box {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
````

上面的 CSS 使得 .box 元素水平垂直居中，核心点通过 translate(-50%, -50%) 来抵消自身一半的偏移量。

既然，有了抵消的思想，我们也可以借助 .avatar 外层元素的反向旋转来抵消 .avatar 的正向旋转。

修改下 HTML 结构：

````html
<div class="wrap">
    <div class="avatar">
        <img src="https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=320178652,790985626&fm=27&gp=0.jpg" />
    </div>
</div>
````

一般的，对于静态元素，我们可以指定具体的值来抵消，比如 60deg，可以用 -60deg（或300deg）来抵消，但是这里我们是动态的，肯定不可能这么写。

对于动态运动的，如果你理解了，可能会更简单：

````css
.wrap {
  width: 300px;
  height: 300px;
  border-radius: 50%;
  background: #007fff;
}
.avatar {
  width: 50px;
  height: 50px;
  margin: 0 auto;
  border-radius: 50%;
  overflow: hidden;
  transform-origin: 50% 150px;
  animation: spin 8s infinite linear;
}
.avatar > img {
  width: 50px;
  height: 50px;
  animation: spin-reverse 8s infinite linear;
}
@keyframes spin {
  to { transform: rotate(1turn); }
}
@keyframes spin-reverse {
  from { transform: rotate(1turn); }
}
````

在上面的 CSS 中，我们新定义了一个 spin-reverse 反向动画，一个结束，一个开始，实现运动抵消，进一步达到始终保持头像正确朝向的效果。

在线DEMO：[https://codepen.io/hcx/pen/VoLjaP](https://codepen.io/hcx/pen/VoLjaP)
